### ISSUE TITLE
Option request

### ISSUE THREAD

**Issue by Scotsgeek** [rrthomas/rpl#11]
One option feature I would like to see in the rpl command:

Display only lines where text changed displaying:
File name
Line number
Original text
Replacement text

There may be places, such as within a comment, that I don't want to see
the text changed that I did not notice before running the command.  The
display could be just the actual text changed or entire lines, as in a
diff or git diff.  

Yes, I know I could run a diff after, but would rather see just after I
run the command.  I might be doing multiple changes on the same file.

With this option in place, I would see any possible mistaken changes.

The -v verbose option only shows the files processed but not the
changes made.

**Comment by rrthomas** [comment]
I think that diff (or a similar tool) is the right thing to use. You can easily make an alias or script to run diff if you want. I have no sense that different users are going to want exactly the same thing or workflow.
