### ISSUE TITLE
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/lib/python3.9/typing.py)

### ISSUE THREAD

**Issue by m-ar-c** [rrthomas/rpl#17]
Hi. I just updated rpl from this repo today. Now I have the following error :
```
# rpl --version

Traceback (most recent call last):
  File "/opt/rpl/rpl", line 30, in <module>
    from typing import (
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/lib/python3.9/typing.py)
```

The command is run inside a `debian 11.5` lxc container.

The file `/usr/lib/python3.9/typing.py` do exists but `grep -i typealias /usr/lib/python3.9/typing.py` yields nothing.

Please tell me If you want me to do more investigation.

**Comment by rrthomas** [comment]
Thanks for noticing this; `TypeAlias` requires Python 3.10. Fortunately, as you can see, it's not actually used in the code. I shall add `pylint` to my armoury and see what other nits I can find.

**Comment by m-ar-c** [comment]
Thanks for the quick fix! I had to additionally install pyhton3-regex, but now rpl works again :)

**Comment by rrthomas** [comment]
Indeed, that's now a mandatory (formerly an optional dependency). It does not seem a big deal, since it's mature and commonly packaged. Requiring it simplifies the code and also testing.
