### ISSUE TITLE
python setup.py build fails on base RHEL9 system

### ISSUE THREAD

**Issue by lcn2** [rrthomas/rpl#19]
The code assumes that certain modules have already been installed.  For example, under a base Linux system with python3, the _setup.py_ fails.  For example:

```sh
python setup.py build
```

on a base Linux system with python3 will generate the following error:

```
Traceback (most recent call last):
  File "/usr/local/src/bin/rpl/rpl-rrthoman/setup.py", line 2, in <module>
    from build_manpages.build_manpages import build_manpages, get_install_cmd, get_build_py_cmd
ModuleNotFoundError: No module named 'build_manpages.build_manpages'
```

Moreover, the _rpl_ code assumes that the following has already been run:

```
python -m pip install regex
```

We recommend that _setup.py_ assist the user with missing modules, perhaps by testing and informing them of the required pip commands in order to proceed OR at a minimum the _README.md_ file should mention the required pip command prerequeists.

**Comment by rrthomas** [comment]
The dependencies are all listed in `setup.cfg`. Running `setup.py` directly is deprecated.

**Comment by rrthomas** [comment]
Done! I have also added `HACKING.md` for hackers and packagers. Thanks!

**Comment by lcn2** [comment]
Thank you and you are welcome.
