### ISSUE TITLE
Efficiency regression

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/rpl#5]
This reported by a user via email:

We use rpl command line in an automatic process. This process was run in Ubuntu 18.04 (rpl 1.5.6) and now run in Ubuntu 20.04 (rpl 1.6.5).

This process with replace several string in a backup file of 2 Gigabytes. With rpl 1.5.6 the execute duration of this process was 10-20 seconds. With rpl 1.6.5 we stoped the process after 30 minutes run.

Finally, we copy old (1.5.6) rpl command line (/usr/bin/rpl) from our old server (Ubuntu 18.04) to new server (Ubuntu 20.04), and the process come back to get same execution times... 10-20 seconds instead almost more than 30 minutes.

**Comment by rrthomas** [comment]
An initial look suggests the problem may be in the `ChainStream` class, which is used with automatic character encoding detection, so I've asked the user to try using `--encoding` as a workaround.

**Comment by goinnn** [comment]
Hi @rrthomas 

I am the user that reported this via e-mail :-)

You are right!

    time rpl "XXXX;" "YYY;" db.15.may.2020.sql --encoding="UTF-8"
    rpl: Replacing "XXX;" with "YYY;" (case sensitive; partial words matched)
    rpl: A total of 0 matches replaced in 1 file searched
    real	0m15,361s
    user	0m11,149s
    sys	0m9,090s

If I specify encoding, I get a nice execution time.

As a tip, and quick fix, I would put a warning log if someone uses the rpl command with files larger than X Megabytes and does not set the encoding

**Comment by rrthomas** [comment]
Thanks very much for the confirmation! Rather than add a warning, I will try to get a fix out as fast as I can.

**Comment by goinnn** [comment]
Nice! :-)

**Comment by rrthomas** [comment]
I had a look at the code, and there are two candidates for the source of the slow-down. The I thought of first (the `ChainStream` class) looks on close inspection as though it's unlikely to be the problem: as far as I can see it passes data through efficiently.

So I wonder instead whether the problem is that the character encoding detector slurps up the entire file trying to work out the encoding.
