### ISSUE TITLE
ignore-case flag behavior change

### ISSUE THREAD

**Issue by jorik392** [rrthomas/rpl#7]
I noticed that with https://github.com/rrthomas/rpl/commit/8dc32334eed207cc01aecca69737a6ce18739f82 the behavior for the --ignore-case flag had changed to try and match capitalization of the match for the replace text as well. 

For my uses the old way was how I had wanted it to work but realized it wasn't doing so in the newer versions of the program. Is there any way to get the old behavior of the ignore case flag? To me the new way seems more suited for something like --ignore-case-smart than --ignore-case.

Thank you

**Comment by rrthomas** [comment]
You're right, these two should be separate options. I'll fix this.
